[package]
name = "one-many"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
one-of-many-proofs = "0.1.0"
rand = "0.7"
merlin = "2.0.0"
curve25519-dalek = "2.1.3"
sha3 = "0.7.0"
